trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build First Job
    - bash: echo $(PipelineLevelVariable)
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(Build.SourcesDirectory)
    - bash: echo $(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
  # - job: SecondJob
  #   steps:
  #   - bash: echo Build Second Job
# - stage: DevDeploy
#   dependsOn: Build
#   jobs:
#   - job: DevDeploy
#     steps:
#     - bash: echo DevDeploy
# - stage: QADeploy
#   dependsOn: Build
#   jobs:
#   - job: QADeploy
#     steps:
#     - bash: echo QADeploy 
# - stage: ProdDeploy
#   dependsOn:
#   - DevDeploy
#   - QADeploy
#   jobs:
#   - job: ProdDeploy
#     steps:
#     - bash: echo ProdDeploy
