trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build First Job
  - job: SecondJob
    steps:
    - bash: echo Build Second Job
- stage: DevDeploy
  dependsOn: Build
  jobs:
  - job: DevDeploy
    steps:
    - bash: echo DevDeploy
- stage: QADeploy
  dependsOn: Build
  jobs:
  - job: QADeploy
    steps:
    - bash: echo QADeploy 
- stage: ProdDeploy
  dependsOn:
  - DevDeploy
  - QADeploy
  jobs:
  - job: ProdDeploy
    steps:
    - bash: echo ProdDeploy
